version: '3'
services:
  nginx:
    image: "islandboy83/book3-nginx"
    hostname: nginx
    mem_limit: 128m
    depends_on:
      - api
      - client
    restart: always
    ports:
      - '80:80'
  api:
    image: "islandboy83/book3-server"
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - PGUSER
      - PGHOST
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
  client:
    environment:
      - WDS_SOCKET_PORT=0
    image: "islandboy83/book3-client"
    hostname: client
    mem_limit: 128m
  worker:
    image: "islandboy83/book3-worker"
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST
      - REDIS_PORT
